export const categories = [
  {
    title: 'BAIN',
    backgroundColor: 'a7a7a7',
    textColor: 'FFFFFF',
    services: [
      {
        id: '143BDC90561',
        title: 'Bain Aura Botanica',
        qualified: true,
      },
      { id: '1638DB9B1', title: 'Balsamo Muschio anti', qualified: true },
      {
        id: '143BDC90511',
        title: 'Crema Anticellulite Elite',
        qualified: true,
      },
      { id: '1630D593541', title: 'Shampoo Verde', qualified: false },
    ],
  },
  {
    title: 'COLORE',
    backgroundColor: 'a7a7a7',
    textColor: 'FFFFFF',
    services: [
      { id: '243BDC90561', title: 'AApofoefe', qualified: true },
      { id: '2638DB9B1', title: 'Niki', qualified: true },
    ],
  },
  {
    title: 'FORNITORE 1',
    backgroundColor: 'a7a7a7',
    textColor: 'FFFFFF',
    services: [
      { id: '343BDC90561', title: 'Colore 10 minuti', qualified: true },
      { id: '3638DB9B1', title: 'Colore completo', qualified: true },
      { id: '343BDC90511', title: 'Colore Future', qualified: true },
    ],
  },
  {
    title: 'FORNITORE 2',
    backgroundColor: 'a7a7a7',
    textColor: 'FFFFFF',
    services: [
      { id: '443BDC90561', title: 'Colore 10 minuti', qualified: true },
      { id: '4638DB9B1', title: 'Colore completo', qualified: true },
      { id: '443BDC90511', title: 'Colore Future', qualified: true },
      { id: '4630D593541', title: 'colore moda estate', qualified: false },
      { id: '463ED593571', title: 'Colore senza amm.', qualified: false },
      { id: '423FDA9A1', title: 'Colore senza ammonia', qualified: false },
    ],
  },
  {
    title: 'FORNITORE 3',
    backgroundColor: 'a7a7a7',
    textColor: 'FFFFFF',
    services: [
      { id: '543BDC90561', title: 'Colore 10 minuti', qualified: true },
      { id: '543BDD9253E21', title: 'Sunshine', qualified: false },
    ],
  },
  {
    title: 'FORNITORE 4',
    backgroundColor: 'a7a7a7',
    textColor: 'FFFFFF',
    services: [
      { id: '643BDC90561', title: 'Colore 10 minuti', qualified: true },
      { id: '643BDC90511', title: 'Colore Future', qualified: true },
      { id: '6630D593541', title: 'colore moda estate', qualified: false },
      { id: '623AD492541', title: 'elumen', qualified: false },
      { id: '6C38DF96581', title: 'Giallo canarino', qualified: false },
      { id: '6430DE9A591', title: 'Manicure 5', qualified: false },
      { id: '6738DA95591', title: 'prova', qualified: false },
      { id: '643BDD9253E21', title: 'Sunshine', qualified: false },
    ],
  },
  {
    title: 'GAMAX',
    backgroundColor: 'a7a7a7',
    textColor: 'FFFFFF',
    services: [
      { id: '743BDC90561', title: 'Colore 10 minuti', qualified: true },
      { id: '7638DB9B1', title: 'Colore completo', qualified: true },
      { id: '763ED593571', title: 'Colore senza amm.', qualified: false },
      { id: '723FDA9A1', title: 'Colore senza ammonia', qualified: false },
      { id: '7D3FD4901', title: 'Deco', qualified: false },
      { id: '7738DA95591', title: 'prova', qualified: false },
      { id: '743BDD9253E21', title: 'Sunshine', qualified: false },
    ],
  },
  {
    title: 'KERASTASE',
    backgroundColor: 'a7a7a7',
    textColor: 'FFFFFF',
    services: [
      { id: '843BDC90511', title: 'Colore Future', qualified: true },
      { id: '8630D593541', title: 'colore moda estate', qualified: false },
      { id: '863ED593571', title: 'Colore senza amm.', qualified: false },
      { id: '823FDA9A1', title: 'Colore senza ammonia', qualified: false },
      { id: '8D3FD4901', title: 'Deco', qualified: false },
      { id: '8738DA95591', title: 'prova', qualified: false },
      { id: '843BDD9253E21', title: 'Sunshine', qualified: false },
    ],
  },
  {
    title: 'LOREAL',
    backgroundColor: 'a7a7a7',
    textColor: 'FFFFFF',
    services: [
      { id: '943BDC90561', title: 'Colore 10 minuti', qualified: true },
      { id: '9638DB9B1', title: 'Colore completo', qualified: true },
      { id: '943BDC90511', title: 'Colore Future', qualified: true },
      { id: '9738DA95591', title: 'prova', qualified: false },
      { id: '943BDD9253E21', title: 'Sunshine', qualified: false },
    ],
  },
  {
    title: 'WELLA',
    backgroundColor: 'a7a7a7',
    textColor: 'FFFFFF',
    services: [
      { id: '1043BDC90561', title: 'Colore 10 minuti', qualified: true },
      { id: '10638DB9B1', title: 'Colore completo', qualified: true },
      { id: '1023FDA9A1', title: 'Colore senza ammonia', qualified: false },
      { id: '10D3FD4901', title: 'Deco', qualified: false },
      { id: '1023AD492541', title: 'elumen', qualified: false },
      { id: '10D38DE95591', title: 'Prova', qualified: false },
      { id: '10738DA95591', title: 'prova', qualified: false },
      { id: '1043BDD9253E21', title: 'Sunshine', qualified: false },
    ],
  },
]
