export const categories = [
  {
    title: 'Colore2',
    backgroundColor: '1dc499',
    textColor: 'FFFFFF',
    services: [
      { id: '143BDC9056', title: 'Colore 10 minuti', qualified: true },
      { id: '1638DB9B', title: 'Colore completo', qualified: true },
      { id: '143BDC9051', title: 'Colore Future', qualified: true },
      { id: '1630D59354', title: 'colore moda estate', qualified: false },
      { id: '163ED59357', title: 'Colore senza amm.', qualified: false },
      { id: '123FDA9A', title: 'Colore senza ammonia', qualified: false },
      { id: '1D3FD490', title: 'Deco', qualified: false },
      { id: '123AD49254', title: 'elumen', qualified: false },
      { id: '1C38DF9658', title: 'Giallo canarino', qualified: false },
      { id: '1430DE9A59', title: 'Manicure 5', qualified: false },
      { id: '1D38DE9559', title: 'Prova', qualified: false },
      { id: '1738DA9559', title: 'prova', qualified: false },
      { id: '143BDD9253E2', title: 'Sunshine', qualified: false },
    ],
  },
  {
    title: 'Body',
    backgroundColor: '2080e9',
    textColor: 'FFFFFF',
    services: [
      { id: '243BDC9056', title: 'Colore 10 minuti', qualified: true },
      { id: '2638DB9B', title: 'Colore completo', qualified: true },
      { id: '2D38DE9559', title: 'Prova', qualified: false },
      { id: '2738DA9559', title: 'prova', qualified: false },
      { id: '243BDD9253E2', title: 'Sunshine', qualified: false },
    ],
  },
  {
    title: 'Aesthetics',
    backgroundColor: '1a7ea0',
    textColor: 'FFFFFF',
    services: [
      { id: '343BDC9056', title: 'Colore 10 minuti', qualified: true },
      { id: '3638DB9B', title: 'Colore completo', qualified: true },
      { id: '343BDC9051', title: 'Colore Future', qualified: true },
    ],
  },
  {
    title: 'Meches',
    backgroundColor: 'ffb300',
    textColor: 'FFFFFF',
    services: [
      { id: '443BDC9056', title: 'Colore 10 minuti', qualified: true },
      { id: '4638DB9B', title: 'Colore completo', qualified: true },
      { id: '443BDC9051', title: 'Colore Future', qualified: true },
      { id: '4630D59354', title: 'colore moda estate', qualified: false },
      { id: '463ED59357', title: 'Colore senza amm.', qualified: false },
      { id: '423FDA9A', title: 'Colore senza ammonia', qualified: false },
    ],
  },
  {
    title: 'Fold',
    backgroundColor: '607d8b',
    textColor: 'FFFFFF',
    services: [
      { id: '543BDC9056', title: 'Colore 10 minuti', qualified: true },
      { id: '543BDD9253E2', title: 'Sunshine', qualified: false },
    ],
  },
  {
    title: 'Solarium',
    backgroundColor: 'ffe903',
    textColor: 'FFFFFF',
    services: [
      { id: '643BDC9056', title: 'Colore 10 minuti', qualified: true },
      { id: '643BDC9051', title: 'Colore Future', qualified: true },
      { id: '6630D59354', title: 'colore moda estate', qualified: false },
      { id: '623AD49254', title: 'elumen', qualified: false },
      { id: '6C38DF9658', title: 'Giallo canarino', qualified: false },
      { id: '6430DE9A59', title: 'Manicure 5', qualified: false },
      { id: '6738DA9559', title: 'prova', qualified: false },
      { id: '643BDD9253E2', title: 'Sunshine', qualified: false },
    ],
  },
  {
    title: 'Cut',
    backgroundColor: '64b5f6',
    textColor: 'FFFFFF',
    services: [
      { id: '743BDC9056', title: 'Colore 10 minuti', qualified: true },
      { id: '7638DB9B', title: 'Colore completo', qualified: true },
      { id: '763ED59357', title: 'Colore senza amm.', qualified: false },
      { id: '723FDA9A', title: 'Colore senza ammonia', qualified: false },
      { id: '7D3FD490', title: 'Deco', qualified: false },
      { id: '7738DA9559', title: 'prova', qualified: false },
      { id: '743BDD9253E2', title: 'Sunshine', qualified: false },
    ],
  },
  {
    title: 'Treatments',
    backgroundColor: '2d89ef',
    textColor: 'FFFFFF',
    services: [
      { id: '843BDC9051', title: 'Colore Future', qualified: true },
      { id: '8630D59354', title: 'colore moda estate', qualified: false },
      { id: '863ED59357', title: 'Colore senza amm.', qualified: false },
      { id: '823FDA9A', title: 'Colore senza ammonia', qualified: false },
      { id: '8D3FD490', title: 'Deco', qualified: false },
      { id: '8738DA9559', title: 'prova', qualified: false },
      { id: '843BDD9253E2', title: 'Sunshine', qualified: false },
    ],
  },
  {
    title: 'Man',
    backgroundColor: 'f88b17',
    textColor: 'FFFFFF',
    services: [
      { id: '943BDC9056', title: 'Colore 10 minuti', qualified: true },
      { id: '9638DB9B', title: 'Colore completo', qualified: true },
      { id: '943BDC9051', title: 'Colore Future', qualified: true },
      { id: '9738DA9559', title: 'prova', qualified: false },
      { id: '943BDD9253E2', title: 'Sunshine', qualified: false },
    ],
  },
  {
    title: 'Various',
    backgroundColor: 'd6006b',
    textColor: 'FFFFFF',
    services: [
      { id: '1043BDC9056', title: 'Colore 10 minuti', qualified: true },
      { id: '10638DB9B', title: 'Colore completo', qualified: true },
      { id: '1023FDA9A', title: 'Colore senza ammonia', qualified: false },
      { id: '10D3FD490', title: 'Deco', qualified: false },
      { id: '1023AD49254', title: 'elumen', qualified: false },
      { id: '10D38DE9559', title: 'Prova', qualified: false },
      { id: '10738DA9559', title: 'prova', qualified: false },
      { id: '1043BDD9253E2', title: 'Sunshine', qualified: false },
    ],
  },
]
